cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [

]

catalog/urls.py
from django.urls import path

from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('',
         views.IndexTemplateView.as_view(),
         name='index'),
    path('items/create',
         views.ItemCreateView.as_view(),
         name='item-create'),
    path('items/list',
         views.ItemListView.as_view(),
         name='item-list'),
    path('items/detail/<slug:slug>',
         views.ItemDetailView.as_view(),
         name='item-detail'),
    path('items/update/<slug:slug>',
         views.ItemUpdateView.as_view(),
         name='item-update'),
    path('items/delete/<slug:slug>',
         views.ItemDeleteView.as_view(),
         name='item-delete'),
]

lizardic_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from django_registration.backends.one_step.views import RegistrationView
# from user.forms import MyUserForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    # path(
    #     'users/register/',
    #     RegistrationView.as_view(form_class=MyUserForm),
    #     name='django_registration_register'
    # ),
    # path('users/', include('django_registration.backends.one_step.urls')),
    # path('users/', include('django.contrib.auth.urls')),
    path('api/v1/', include('djoser.urls')),
    path('api/v1/', include('djoser.urls.authtoken')),
    path('api/v1/', include('catalog_api.urls')),
    path('api/v1/', include('cart_api.urls')),
    path('', include('catalog.urls')),
    path('', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/footer.html
<footer class="modal-footer" style="margin-top: 25px">
    <ul class="list-group list-group-horizontal">
{#        <li class="list-group-item"><a href="{% url 'catalog:about' %}">About</a></li>#}
{#        <li class="list-group-item"><a href="{% url 'catalog:contact' %}">Contact</a></li>#}
    </ul>
    &copy chook 2023
</footer>

templates/include/header.html
<header style="margin-bottom: 20px">
  <ul class="modal-header" style="text-align: center">
    <li class="list-inline-item"><a href="{% url 'catalog:index' %}">Главная страница</a></li>
    <li class="list-inline-item"><a href="{% url 'catalog:item-list' %}">Список товаров</a></li>
    {% if user.is_authenticated %}
      <li>User: {{ user.get_username }} <a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
    {% else %}
      <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
    {% endif %}
  </ul>
</header>